edition = "2018"
max_width = 90
hard_tabs = false
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
fn_args_layout = "Tall"
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true