[[packages]]
name = "godot"
location = "github:godotengine/godot"
version = "3.2-stable"

[[packages]]
name = "powershell"
location = "github:powershell/powershell"
version = "v6.2.4"

[[packages]]
name = "docker-toolbox"
location = "github:docker/toolbox"
version = "v19.03.1"

[[packages]]
name = "cutter"
location = "github:radareorg/cutter"
version = "v1.10.1"

# [[packages]]
# name = "gimp"
# location = "package:gimp"
# version = "2.10.14"

# [[packages]]
# name = "krita"
# location = "package:krita"
# version = "4.2.8"

# [[packages]]
# name = "blender"
# location = "package:blender"
# version = "2.81a"